module.exports = {
  KhachHang: require('./khachHang'),
  User: require('./user'),
  NhaXe: require('./nhaXe'),
  ChuyenXe: require('./chuyenXe'),
  VeXe: require('./veXe'),
  DanhGia: require('./danhGia'),
  ThanhToan: require('./thanhToan'),
  NhanVien: require('./nhanVien'),
  Xe: require('./xe'),
  LoaiXe: require('./loaiXe'),
  LichSuVeXe: require('./lichSuVeXe'),
  CSKH: require('./cskh'),
  ThongBao: require('./thongBao'),
  TuyenXe: require('./tuyenXe'),
  KhuyenMai: require('./khuyenMai'),
  SoGheSoGiuong: require('./soGheSoGiuong'),
  TaiXe: require('./taiXe'),
};